version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2807MCSPPPProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_2807mcsppp.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.siqa_git_2807mcsppp.integrations:Copy_deepclonetest
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.siqa_git_2807mcsppp.integrations:Copy_refdaf
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_2807mcsppp.referencedata:refData
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_2807mcsppp.integrations:GitSyncFlow
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.siqa_git_2807mcsppp.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_2807mcsppp.integrations:refdaf
  packages:
  - name: SIQA_GIT_2807MCSPPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
