version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2807MCSPPPProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
